### ISSUE TITLE
Your repo should follow Hacktoberfest 2024 Guidelines 📝

### ISSUE THREAD

**Issue by Parnab03** [ghostmkg/web-development#31]
According to https://hacktoberfest.com/participation/#maintainers your repository is not following the guidelines given by Hacktoberfest 2024.
   Here I can help you, myself also maintaining a Hacktoberfest 2024 repository https://github.com/sudo-parnab/Its-webtober.
I can fix your repo by adding CONTRIBUTING.md file and a code of conduct and make necessary changes, should I do this?

Give me a reply under this issue, and assigned this issue to me.
Thank You! 🙏

**Comment by ghostmkg** [comment]
Go ahead. And make the changes.

**Comment by Parnab03** [comment]
> Go ahead. And make the changes.

assigned this issue to me
On the right hand side there is a Assignees section, here type my Github username Parnab03 and assigned it to me
![Screenshot 2024-10-06 at 13-30-27 Your repo should follow Hacktoberfest 2024 Guidelines 📝 · Issue #31 · ghostmkg_web-development](https://github.com/user-attachments/assets/78ac4a58-9aa6-4549-be42-6b7a92d99dad)

**Comment by Parnab03** [comment]
Thank you for assigned me, now check the PR
