### ISSUE TITLE
I WANT ADD MY COLLEGE WEBSITE

### ISSUE THREAD

**Issue by Darshan3690** [ghostmkg/web-development#67]
COLLEGE NAME IS NOVA UNIVERSITY .
IN THIS WEBSITE  WE HAVE VISITOR MANAGEMENT DASHBOARD  .

**Comment by ghostmkg** [comment]
@Darshan3690 Please raise PR for this issue or I will close this issue or reassign it to someone else.

**Comment by Darshan3690** [comment]
please check   add my university website #98 pr.

**Comment by ghostmkg** [comment]
Closing this issue.
