### ISSUE TITLE
I want to add a quiz time table generator for collage

### ISSUE THREAD

**Issue by rahulbamnuya** [ghostmkg/web-development#73]

**Comment by ghostmkg** [comment]
@rahulbamnuya Please add the details or else I will close this issue.

**Comment by rahulbamnuya** [comment]
**Teacher Quiz Duty and Timetable Generation System**
This web-based application automates the process of assigning quiz duties to teachers and generating a timetable for college quizzes. Built using Node.js, Express.js, Multer, and Google Generative AI, the system allows admins to upload teacher and subject details via images, extract names automatically, and generate a balanced quiz timetable.

**Key Features:**
Teacher and Subject Management: Upload teacher/subject images and extract names using Google Generative AI.
Quiz Timetable Generation: Automatically generate timetables based on teacher availability and quiz slots (5 per day).
Teacher Availability: Manage and schedule teacher availability to prevent clashes.
View and Edit Timetable: Display timetables with day-wise teacher assignments.
Technologies Used:
Node.js, Express.js
Multer for image uploads
Google Generative AI for image processing
EJS for dynamic HTML rendering
Moment.js for date handling
**Getting Started:**
Clone the repository.
Install dependencies with npm install.
Set your Google API Key as an environment variable.
Start the server with npm start.

**Comment by ghostmkg** [comment]
@rahulbamnuya  Please raise the PR or I will close this issue
